[package]
name = "rust"
version = "0.1.0"
authors = ["Richard Whitehouse <richard.whitehouse@metaswitch.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.2"
log = "0.4.11"
