mod eight;
mod eleven;
mod fifteen;
mod five;
mod four;
mod fourteen;
mod nine;
mod one;
mod seven;
mod six;
mod ten;
mod thirteen;
mod three;
mod twelve;
mod two;

mod intcode;

fn main() {
    one::run_a();
    one::run_b();
    two::run_a();
    two::run_b();
    three::run_a();
    three::run_b();
    four::run_a();
    four::run_b();
    five::run_a();
    five::run_b();
    six::run_a();
    six::run_b();
    seven::run_a();
    seven::run_b();
    eight::run_a();
    eight::run_b();
    nine::run_a();
    nine::run_b();
    ten::run_a();
    ten::run_b();
    eleven::run_a();
    eleven::run_b();
    twelve::run_a();
    twelve::run_b();
    thirteen::run_a();
    thirteen::run_b();
    fourteen::run_a();
    fourteen::run_b();
    fifteen::run_a();
    fifteen::run_b();
}
